services:
  - type: web
    name: ai-voice-detection-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --index-url https://download.pytorch.org/whl/cpu -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_KEY
        value: hackathon-secret-key
      - key: HF_HOME
        value: /opt/render/project/src/.cache

