services:
  - type: web
    name: ai-voice-detection-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && pip install -r requirements-torch.txt --index-url https://download.pytorch.org/whl/cpu
    startCommand: gunicorn app:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_KEY
        value: hackathon-secret-key
      - key: HF_HOME
        value: /opt/render/project/src/.cache

